### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/ansible-tensorflow#8]
**Describe the bug**

run the command "/tensorflow/bin/tensorboard --version_tb", can not display the tensorflow version.
  
![image](https://user-images.githubusercontent.com/54173243/154393979-6ba0741b-622b-4bd4-ba14-67e912264c52.png)
  
![image](https://user-images.githubusercontent.com/54173243/154394141-57fa82a9-2aea-4cd2-9b19-a832df4a893a.png)

## Deployment method

- [x] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [x] Other (You should describe it)   

## System Environment

**Application Version**

Tensorflow 2.8.0 

**OS**

- [ ] Ubuntu18.x
- [x] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [x] Azure
- [ ] Aws
- [x] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
/data/apps/tensorflow/bin/tensorboard --version_tb
